title: A Freeholder
author: Jim Moore
email: ijimmoore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's see if we can give you an idea of what it's like spending 
  some time social distancing with a wife and two cats in Freehold, NJ

# social links
twitter_username: ijimmoore # DO NOT include the @ character, or else the build will fail!
github_username:  ijimmoore # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
